version: '2'
services:
  ca-base:
    image: hyperledger/fabric-ca
    env_file:
      - .env
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server/ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - net
    volumes:
      - ../artifacts:/opt/artifacts
