version: '2'
services:
  base-jincor-ca:
    image: registry.jincor.com/hyperledger/fabric-ca:latest
    restart: always
    env_file:
      - .env
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server/
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    command: sh -c "fabric-ca-server start"
    networks:
      - net
