version: '2'
services:
  base-kafka:
    image: registry.jincor.com/hyperledger/fabric-kafka:latest
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024       # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.jincor.com:2181,zookeeper1.jincor.com:2181,zookeeper2.jincor.com:2181
    ports:
      - 9092
    mem_limit: 768m
    networks:
      - jincormetanetwork
