version: '2'

networks:
  # subnet -> 172.124.0.0/24
  jincormetanetwork:
    external: true

services:
  cli.jincor.com:
    container_name: cli.jincor.com
    image: jincort/hlf-tools:x86_64-1.1.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=jincormetanetwork
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.network.jincor.com:7051
      - CORE_PEER_TLS_ENABLED=${TLS_ENABLED}
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/sandbox/crypto-config/peerOrganizations/network.jincor.com/peers/peer0.network.jincor.com/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/opt/sandbox/crypto-config/peerOrganizations/network.jincor.com/peers/peer0.network.jincor.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/sandbox/crypto-config/peerOrganizations/network.jincor.com/peers/peer0.network.jincor.com/tls/server.key
      - CORE_PEER_MSPCONFIGPATH=/opt/sandbox/crypto-config/peerOrganizations/network.jincor.com/users/Admin@network.jincor.com/msp
    working_dir: /opt/gopath/src/
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincodes/src/github.com/JincorTech:/opt/gopath/src/github.com/JincorTech/
      - ../bootstrap/:/opt/sandbox/
    networks:
      - jincormetanetwork

  zookeeper0.jincor.com:
    container_name: zookeeper0.jincor.com
    extends:
      file: base-zookeeper.yaml
      service: base-zookeeper
    volumes:
      - zooData0:/data
    environment:
      - ZOO_MY_ID=1

  zookeeper1.jincor.com:
    container_name: zookeeper1.jincor.com
    extends:
      file: base-zookeeper.yaml
      service: base-zookeeper
    volumes:
      - zooData1:/data
    environment:
      - ZOO_MY_ID=2

  zookeeper2.jincor.com:
    container_name: zookeeper2.jincor.com
    extends:
      file: base-zookeeper.yaml
      service: base-zookeeper
    volumes:
      - zooData2:/data
    environment:
      - ZOO_MY_ID=3

  kafka0.jincor.com:
    container_name: kafka0.jincor.com
    extends:
      file: base-kafka.yaml
      service: base-kafka
    volumes:
      - kafkaData0:/logs
    environment:
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper0.jincor.com
      - zookeeper1.jincor.com
      - zookeeper2.jincor.com

  kafka1.jincor.com:
    container_name: kafka1.jincor.com
    extends:
      file: base-kafka.yaml
      service: base-kafka
    volumes:
      - kafkaData1:/logs
    environment:
      - KAFKA_BROKER_ID=2
    depends_on:
      - zookeeper0.jincor.com
      - zookeeper1.jincor.com
      - zookeeper2.jincor.com

  kafka2.jincor.com:
    container_name: kafka2.jincor.com
    extends:
      file: base-kafka.yaml
      service: base-kafka
    volumes:
      - kafkaData2:/logs
    environment:
      - KAFKA_BROKER_ID=3
    depends_on:
      - zookeeper0.jincor.com
      - zookeeper1.jincor.com
      - zookeeper2.jincor.com

  kafka3.jincor.com:
    container_name: kafka3.jincor.com
    extends:
      file: base-kafka.yaml
      service: base-kafka
    volumes:
      - kafkaData3:/logs
    environment:
      - KAFKA_BROKER_ID=4
    depends_on:
      - zookeeper0.jincor.com
      - zookeeper1.jincor.com
      - zookeeper2.jincor.com

  ca.orderer.jincor.com:
    container_name: ca.orderer.jincor.com
    extends:
      file: base-jincor-ca.yaml
      service: base-jincor-ca
    volumes:
      - caOrdererCrypto:/etc/hyperledger/fabric-ca-server/
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.10
    ports:
      - 7055:7054

  ca.network.jincor.com:
    container_name: ca.network.jincor.com
    extends:
      file: base-jincor-ca.yaml
      service: base-jincor-ca
    volumes:
      - caNetworkCrypto:/etc/hyperledger/fabric-ca-server/
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.11
    ports:
      - 7054:7054

  orderer0.orderer.jincor.com:
    container_name: orderer0.orderer.jincor.com
    extends:
      file: base-jincor-orderer.yaml
      service: base-jincor-orderer
    environment:
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderers/orderer0.orderer.jincor.com/msp
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderers/orderer0.orderer.jincor.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderers/orderer0.orderer.jincor.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderers/orderer0.orderer.jincor.com/tls/ca.crt,/etc/hyperledger/crypto/peers-tls/tlsca-cert.pem]
    volumes:
      - ordererCrypto:/etc/hyperledger/crypto/orderers/:ro
      - ordererGenesis:/var/hyperledger/orderer/:ro
      - networkCryptoTls:/etc/hyperledger/crypto/peers-tls/:ro
      - ordererData0:/var/hyperledger
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.20
    ports:
      - 7050:7050
    depends_on:
      - kafka0.jincor.com
      - kafka1.jincor.com
      - kafka2.jincor.com
      - kafka3.jincor.com

  orderer1.orderer.jincor.com:
    container_name: orderer1.orderer.jincor.com
    extends:
      file: base-jincor-orderer.yaml
      service: base-jincor-orderer
    environment:
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderers/orderer1.orderer.jincor.com/msp
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderers/orderer1.orderer.jincor.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderers/orderer1.orderer.jincor.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderers/orderer1.orderer.jincor.com/tls/ca.crt,/etc/hyperledger/crypto/peers-tls/tlsca-cert.pem]
    volumes:
      - ordererCrypto:/etc/hyperledger/crypto/orderers/:ro
      - ordererGenesis:/var/hyperledger/orderer/:ro
      - networkCryptoTls:/etc/hyperledger/crypto/peers-tls/:ro
      - ordererData1:/var/hyperledger
    ports:
      - 8050:7050
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.21
    depends_on:
      - kafka0.jincor.com
      - kafka1.jincor.com
      - kafka2.jincor.com
      - kafka3.jincor.com

  orderer2.orderer.jincor.com:
    container_name: orderer2.orderer.jincor.com
    extends:
      file: base-jincor-orderer.yaml
      service: base-jincor-orderer
    environment:
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderers/orderer2.orderer.jincor.com/msp
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderers/orderer2.orderer.jincor.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderers/orderer2.orderer.jincor.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderers/orderer2.orderer.jincor.com/tls/ca.crt,/etc/hyperledger/crypto/peers-tls/tlsca-cert.pem]
    volumes:
      - ordererCrypto:/etc/hyperledger/crypto/orderers/:ro
      - ordererGenesis:/var/hyperledger/orderer/:ro
      - networkCryptoTls:/etc/hyperledger/crypto/peers-tls/:ro
      - ordererData2:/var/hyperledger
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.22
    ports:
      - 9050:7050
    depends_on:
      - kafka0.jincor.com
      - kafka1.jincor.com
      - kafka2.jincor.com
      - kafka3.jincor.com

  peer0.network.jincor.com:
    container_name: peer0.network.jincor.com
    extends:
      file: base-jincor-peer.yaml
      service: base-jincor-peer
    environment:
      - CORE_PEER_ID=peer0.network.jincor.com
      - CORE_PEER_ADDRESS=peer0.network.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.network.jincor.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.network.jincor.com:7051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peers/peer0.network.jincor.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peers/peer0.network.jincor.com/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peers/peer0.network.jincor.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peers/peer0.network.jincor.com/tls/server.key
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.30
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0.orderer.jincor.com
      - orderer1.orderer.jincor.com
      - orderer2.orderer.jincor.com
    volumes:
      - networkCrypto:/etc/hyperledger/crypto/peers:ro
      - networkPeerData0:/var/hyperledger

  peer1.network.jincor.com:
    container_name: peer1.network.jincor.com
    extends:
      file: base-jincor-peer.yaml
      service: base-jincor-peer
    environment:
      - CORE_PEER_ID=peer1.network.jincor.com
      - CORE_PEER_ADDRESS=peer1.network.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.network.jincor.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.network.jincor.com:7051
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peers/peer1.network.jincor.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peers/peer1.network.jincor.com/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peers/peer1.network.jincor.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peers/peer1.network.jincor.com/tls/server.key
    networks:
      jincormetanetwork:
        ipv4_address: 172.124.0.31
    ports:
      - 7056:7051
      - 7058:7053
    depends_on:
      - peer0.network.jincor.com
      - orderer0.orderer.jincor.com
      - orderer1.orderer.jincor.com
      - orderer2.orderer.jincor.com
    volumes:
      - networkCrypto:/etc/hyperledger/crypto/peers:ro
      - networkPeerData1:/var/hyperledger

volumes:

  zooData0:
    external:
      name: jincormetanetZooData0
  zooData1:
    external:
      name: jincormetanetZooData1
  zooData2:
    external:
      name: jincormetanetZooData2

  kafkaData0:
    external:
      name: jincormetanetKafkaData0
  kafkaData1:
    external:
      name: jincormetanetKafkaData1
  kafkaData2:
    external:
      name: jincormetanetKafkaData2
  kafkaData3:
    external:
      name: jincormetanetKafkaData3

  caOrdererCrypto:
    external:
      name: jincormetanetCaOrderers
  caNetworkCrypto:
    external:
      name: jincormetanetCaNetwork

  ordererGenesis:
    external:
      name: jincormetanetOrdererGenesis
  ordererCrypto:
    external:
      name: jincormetanetOrdererCryptodata
  ordererCryptoTls:
    external:
      name: jincormetanetOrdererCryptodataTlsca

  ordererData0:
    external:
      name: jincormetanetOrdererData0
  ordererData1:
    external:
      name: jincormetanetOrdererData1
  ordererData2:
    external:
      name: jincormetanetOrdererData2

  networkCrypto:
    external:
      name: jincormetanetNetworkCryptodata
  networkCryptoTls:
    external:
      name: jincormetanetNetworkCryptodataTlsca

  networkPeerData0:
    external:
      name: jincormetanetNetworkPeerData0
  networkPeerData1:
    external:
      name: jincormetanetNetworkPeerData1
